# Generated by Django 3.1.3 on 2020-11-07 14:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('name_long', models.CharField(blank=True, max_length=254, null=True)),
                ('formal_en', models.CharField(blank=True, max_length=254, null=True)),
                ('sov_a3', models.CharField(blank=True, max_length=254, null=True)),
                ('postal', models.CharField(blank=True, max_length=254, null=True)),
                ('abbrev', models.CharField(blank=True, max_length=254, null=True)),
                ('continent', models.CharField(blank=True, max_length=254, null=True)),
                ('region_un', models.CharField(blank=True, max_length=254, null=True)),
                ('subregion', models.CharField(blank=True, max_length=254, null=True)),
                ('region_wb', models.CharField(blank=True, max_length=254, null=True)),
                ('pop_est', models.BigIntegerField(blank=True, null=True)),
                ('pop_rank', models.BigIntegerField(blank=True, null=True)),
                ('gdp_md_est', models.DecimalField(blank=True, decimal_places=2, max_digits=65535, null=True)),
                ('pop_year', models.BigIntegerField(blank=True, null=True)),
                ('lastcensus', models.BigIntegerField(blank=True, null=True)),
                ('gdp_year', models.BigIntegerField(blank=True, null=True)),
                ('economy', models.CharField(blank=True, max_length=254, null=True)),
                ('income_grp', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Earthquakes',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(blank=True, max_length=254, null=True)),
                ('time', models.CharField(blank=True, max_length=254, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=2, max_digits=65535, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=2, max_digits=65535, null=True)),
                ('type', models.CharField(blank=True, max_length=254, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('depth_erro', models.DecimalField(blank=True, db_column='depth erro', decimal_places=2, max_digits=65535, null=True)),
                ('depth_seis', models.DecimalField(blank=True, db_column='depth seis', decimal_places=2, max_digits=65535, null=True)),
                ('magnitude', models.DecimalField(blank=True, decimal_places=2, max_digits=65535, null=True)),
                ('magnitud_1', models.CharField(blank=True, max_length=254, null=True)),
                ('magnitud_2', models.DecimalField(blank=True, decimal_places=2, max_digits=65535, null=True)),
                ('magnitud_3', models.DecimalField(blank=True, decimal_places=2, max_digits=65535, null=True)),
                ('azimuthal', models.DecimalField(blank=True, decimal_places=2, max_digits=65535, null=True)),
                ('horizontal', models.DecimalField(blank=True, decimal_places=2, max_digits=65535, null=True)),
                ('horizont_1', models.DecimalField(blank=True, decimal_places=2, max_digits=65535, null=True)),
                ('root_mean', models.DecimalField(blank=True, db_column='root mean', decimal_places=2, max_digits=65535, null=True)),
                ('id', models.CharField(blank=True, max_length=254, null=True)),
                ('source', models.CharField(blank=True, max_length=254, null=True)),
                ('location_s', models.CharField(blank=True, db_column='location s', max_length=254, null=True)),
                ('magnitud_4', models.CharField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'earthquakes',
                'managed': False,
            },
        ),
    ]
